//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "consumption_record"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: i32,
    pub user: i32,
    pub consumable: Option<i32>,
    pub composite_consumable: Option<i32>,
    pub date_time: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    User,
    Consumable,
    CompositeConsumable,
    DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    CompositeConsumable,
    Consumable,
    UserAccounts,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::User => ColumnType::Integer.def(),
            Self::Consumable => ColumnType::Integer.def().null(),
            Self::CompositeConsumable => ColumnType::Integer.def().null(),
            Self::DateTime => ColumnType::Timestamp.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::CompositeConsumable => Entity::belongs_to(super::composite_consumable::Entity)
                .from(Column::CompositeConsumable)
                .to(super::composite_consumable::Column::Id)
                .into(),
            Self::Consumable => Entity::belongs_to(super::consumable::Entity)
                .from(Column::Consumable)
                .to(super::consumable::Column::Id)
                .into(),
            Self::UserAccounts => Entity::belongs_to(super::user_accounts::Entity)
                .from(Column::User)
                .to(super::user_accounts::Column::Id)
                .into(),
        }
    }
}

impl Related<super::composite_consumable::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompositeConsumable.def()
    }
}

impl Related<super::consumable::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Consumable.def()
    }
}

impl Related<super::user_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
