//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub mod prelude;

pub mod composite_consumable;
pub mod composite_consumable_nutrients;
pub mod consumable;
pub mod consumption_record;
pub mod nutrient_targets;
pub mod nutrients;
pub mod seaql_migrations;
pub mod sessions;
pub mod units;
pub mod users;
