//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

pub use super::composite_consumable::Entity as CompositeConsumable;
pub use super::composite_consumable_nutrients::Entity as CompositeConsumableNutrients;
pub use super::consumable::Entity as Consumable;
pub use super::consumption_record::Entity as ConsumptionRecord;
pub use super::nutrient_targets::Entity as NutrientTargets;
pub use super::nutrients::Entity as Nutrients;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::sessions::Entity as Sessions;
pub use super::units::Entity as Units;
pub use super::users::Entity as Users;
