//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub use super::composite_consumable::Entity as CompositeConsumable;
pub use super::composite_consumable_nutrients::Entity as CompositeConsumableNutrients;
pub use super::consumable::Entity as Consumable;
pub use super::consumption_record::Entity as ConsumptionRecord;
pub use super::date::Entity as Date;
pub use super::nutrient_targets::Entity as NutrientTargets;
pub use super::nutrients::Entity as Nutrients;
pub use super::time::Entity as Time;
pub use super::units::Entity as Units;
pub use super::users::Entity as Users;
